# Generated by Django 5.1.4 on 2025-01-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.IntegerField(max_length=100)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('autor', models.ManyToManyField(to='radiovirgenBD.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('podcast_likes', models.ManyToManyField(related_name='usuarios_likes', to='radiovirgenBD.podcast')),
                ('podcast_lista_escuchar', models.ManyToManyField(related_name='usuarios_pendientes', to='radiovirgenBD.podcast')),
                ('podcast_seguido', models.ManyToManyField(related_name='seguidores', to='radiovirgenBD.podcast')),
                ('programas_likes', models.ManyToManyField(related_name='usuarios_programas_likes', to='radiovirgenBD.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reproduccion', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.podcast')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'podcast')},
            },
        ),
    ]
