# Generated by Django 5.1.4 on 2025-01-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0002_remove_usuario_podcast_likes_podcast_enlace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duracion',
            field=models.IntegerField(),
        ),
    ]
