# Generated by Django 5.1.4 on 2025-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0003_alter_podcast_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='podcast',
            field=models.ManyToManyField(to='radiovirgenBD.podcast'),
        ),
    ]
