# Generated by Django 5.1.4 on 2025-02-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0005_alter_reproduccion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nick',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
