# Generated by Django 5.1.4 on 2025-02-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0007_remove_usuario_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nick',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
