# Generated by Django 5.1.4 on 2025-02-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0003_remove_usuario_podcast_lista_escuchar_and_more'),
        ('radiovirgenBD', '0008_usuario_nick'),
    ]

    operations = [
    ]
