# Generated by Django 5.1.4 on 2025-02-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0009_merge_20250218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nick',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='podcast_likes',
            field=models.ManyToManyField(blank=True, related_name='usu_podcast_like', to='radiovirgenBD.podcast'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='podcast_pendientes',
            field=models.ManyToManyField(blank=True, related_name='podcast_pendientes', to='radiovirgenBD.podcast'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='programa_seguido',
            field=models.ManyToManyField(blank=True, related_name='prog_seguido', to='radiovirgenBD.programa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='programas_likes',
            field=models.ManyToManyField(blank=True, related_name='usu_programas_like', to='radiovirgenBD.programa'),
        ),
        migrations.AlterUniqueTogether(
            name='reproduccion',
            unique_together={('usuario', 'podcast', 'fecha_reproduccion')},
        ),
    ]
