# Generated by Django 5.1.4 on 2025-02-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0010_alter_usuario_nick_alter_usuario_podcast_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('nombreTitular', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_usuario', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.IntegerField()),
                ('nombreTitular', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='metodo_por_defecto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.usuario')),
                ('pago_tarjeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.pagotarjeta')),
                ('paypal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.paypal')),
                ('transferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radiovirgenBD.transferencia')),
            ],
        ),
    ]
