# Generated by Django 5.1.4 on 2025-02-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiovirgenBD', '0011_pagotarjeta_paypal_transferencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='num_tarjeta',
            new_name='num_cuenta',
        ),
    ]
